from app.models.user import User
from app.models.candidate import Candidate
from app.models.candidate_preference import CandidatePreference
from app.models.candidate_skill import CandidateSkill
from app.models.company import Company
from app.models.education import Education
from app.models.experience import Experience
from app.models.job import Job
from app.models.job_skill import JobSkill
from app.models.application import Application
from app.models.match_result import MatchResult
from app.models.project import Project
from app.models.resume import Resume
from app.models.skill import Skill
from app.models.notification import Notification